Refactor/auto gas
burnt-labs/xion.js pull request #227
Opened 2024-10-11 16:29 UTC by BurntVal

2024-10-11 20:05 UTC, justinbarry commented on packages/abstraxion-core/src/GranteeSignerClient.ts
> +    fee: StdFee | "auto" | number = "auto",
We should keep this api inline with the cosmjs interface
```suggestion
    fee: StdFee | "auto" | number,
```

2024-10-11 20:09 UTC, justinbarry requested changes
One change, also need a change set

2024-10-11 20:14 UTC, justinbarry commented on packages/abstraxion-core/src/GranteeSignerClient.ts
> +      const chainId = await this.getChainId();
Couldn't we pass this in when it is instantiated in the provider?

2024-10-21 23:51 UTC, justinbarry approved these changes
LGTM

2024-10-29 21:47 UTC, justinbarry approved these changes
IGTM

2024-10-29 21:59 UTC, BurntNerve approved these changes
Looks good

2024-10-29 22:00 UTC, merged