ESLint and Typing Fixes for Abstraxion and Signers packages
burnt-labs/xion.js pull request #82
Opened 2024-02-12 15:51 UTC by BurntNerve

2024-02-12 17:50 UTC, justinbarry commented on packages/abstraxion/src/GranteeSignerClient.ts
> +    // eslint-disable-next-line @typescript-eslint/no-unnecessary-condition
Can we turn off the rule instead of using ignores.

2024-02-12 17:54 UTC, justinbarry commented on packages/abstraxion/src/components/Abstraxion/index.tsx
> +  }, [onClose, setShowModal]);
What does this fix?

2024-02-12 18:00 UTC, justinbarry commented on packages/signers/.eslintrc.js
> +  rules: {
Should we do this for all packages?

2024-02-12 18:11 UTC, justinbarry requested changes
A few feedback items but otherwise looks good!

2024-02-12 18:11 UTC, justinbarry commented on packages/signers/src/signers/jwt-signer.ts
> +   * @param signerAddress -
Does this need a description?

2024-02-12 18:11 UTC, justinbarry commented on packages/signers/src/signers/utils/client.ts
> +   * @param fee -
Descriptions if possible

2024-02-12 18:11 UTC, justinbarry commented on packages/abstraxion/utils/queries.ts
> -import { gql } from "@apollo/client";
Do we need to remove this import from package.json?

2024-03-04 20:17 UTC, BurntVal approved these changes
LGTM

2024-03-22 21:12 UTC, justinbarry commented
@BurntNerve What remains to be done here?

2024-06-24 17:30 UTC, closed without merging

2024-06-24 17:30 UTC, justinbarry commented
Was taken care of in another PR.